[package]
name = "set1-2"
version = "0.1.0"
authors = ["BonusPlay <root@bonusplay.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.3.2"